archetypeDir           = "archetypes"
author                 = "amdelamar"
baseUrl                = "https://amdelamar.com/blog"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "osseous"
themesDir              = "themes"
title                  = "RamblingWare"
enableEmoji            = true
defaultContentLanguage = "en"

[blackfriday]
  angledQuotes = true
  hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  twitter_username = "amdelamar"
  paginate = 6
